export const AFF_MODAL_MENU     = "AFF_MODAL_MENU";
export const CHANGE_MENU_DATA   = "CHANGE_MENU_DATA";
export const AFF_MODAL_PRODUIT  = "AFF_MODAL_PRODUIT";
export const AFF_LOADING_MENU   = "AFF_LOADING_MENU";

